//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT_Tuan4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laptop
    {
        public int ID { get; set; }
        public string Company { get; set; }
        public string Product { get; set; }
        public string TypeName { get; set; }
        public Nullable<double> Inches { get; set; }
        public string ScreenResolution { get; set; }
        public string Cpu { get; set; }
        public string Gen { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<int> Ram { get; set; }
        public string Memory { get; set; }
        public string Gpu { get; set; }
        public string OpSys { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Price_euros { get; set; }
    }
}
